// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRNjmSBMhDKOW7dtCtAwrcg_As2yEV9G0',
    appId: '1:878800891884:web:3a3c40b88853dd18911ac9',
    messagingSenderId: '878800891884',
    projectId: 'recipe-e26bc',
    authDomain: 'recipe-e26bc.firebaseapp.com',
    storageBucket: 'recipe-e26bc.firebasestorage.app',
    measurementId: 'G-E61FKP8MEZ',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAsRiRQ-AvdFYTkjbpPeZp5RVtGv6NWuk',
    appId: '1:878800891884:android:c3d6c22624a53605911ac9',
    messagingSenderId: '878800891884',
    projectId: 'recipe-e26bc',
    storageBucket: 'recipe-e26bc.firebasestorage.app',
  );
}
